### ISSUE TITLE
Uninstall scripts

### ISSUE THREAD

**Issue by jorge-plaza** [jgregmac/hyperv-fix-for-devs#14]
As long as this scripts are not needed anymore as pointed out in the README, how can I uninstall the scripts from my system?

I can not find in the help the way to do it.

Thanks

**Comment by jgregmac** [comment]
1.  Remove the scheduled task named "WSL Fix Task - On Startup" that was created by the installer.  You can use the "Task Scheduler" app to find and delete this task.
  2.  Delete the directory "WSL-Network-Fix' from your User Profile directory (This is the directory specified by the USERPROFILE environment variable, which you can access using "%USERPROFILE%" in Explorer path bar, or "cd $ENV:USERPROFILE" in Powershell.

The lastest WSL, version 2.0.6.0, features a "mirrored" networking mode option which will make even the Reg key solution obsolete, although I am finding that mirrored mode is a bit to squirrelly for my uses.  Hopefully with the next release we will be able to put all of these troubles behind us.

-Greg Mackinnon

________________________________
From: Jorge Plaza ***@***.***>
Sent: Friday, November 3, 2023 12:04 PM
To: jgregmac/hyperv-fix-for-devs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jgregmac/hyperv-fix-for-devs] Uninstall scripts (Issue #14)


As long as this scripts are not needed anymore as pointed out in the README, how can I uninstall the scripts from my system?

I can not find in the help the way to do it.

Thanks
