### ISSUE TITLE
Not working with GlobalProtect

### ISSUE THREAD

**Issue by davidberglund** [jgregmac/hyperv-fix-for-devs#3]
Is this script known to work with GlobalProtect? It doesn't work for me. I have disabled the automatic generation of resolv.conf (that fixed the network issues back when I used AnyConnect). Thank you for sharing this script btw, hope I can make it work with GlobalProtect.

**Comment by jgregmac** [comment]
Apologies for the delay, sorry I have no idea if it works with GlobalProtect.  It should, as long as GlobalProtect does not much with your routing tables in any way more invasive than AnyConnect, and provided that you are fully aware of which RFC1918 private addresses ranges are NOT in use by your company.
