### ISSUE TITLE
Get-Help ... -examples not fully implemented

### ISSUE THREAD

**Issue by mrkanaly** [jgregmac/hyperv-fix-for-devs#5]
## Expected Behavior

Per the remark issued from `Get-Help .\Install-DeterministicNetwork.ps1`, when the `-examples` option is used, examples should be given on how to use this script. 

## Current Behavior

Examples are not given.

```
PS C:\Users\kanaly\wsl\hyperv-fix-for-devs> Get-Help .\Install-DeterministicNetwork.ps1 -examples

NAME
    C:\Users\kanaly\wsl\hyperv-fix-for-devs\Install-DeterministicNetwork.ps1

SYNOPSIS
    Installation Script for the Hyper-V / WSL2 Network Fix for Developers


PS C:\Users\kanaly\wsl\hyperv-fix-for-devs>
```

## Possible Solution
Implement examples to help users use the script. 

## Steps to Reproduce

1. From a powershell prompt
2. Execute: `Get-Help .\Install-DeterministicNetwork.ps1 -examples`

## Context (Environment)
First attempt to use the tool, from an admin powershell prompt. 

## Detailed Description

At least one example showing how to configure a particular network other than the default selected. Bonus points for providing networks of both HyperV and WSL in each class.

**Comment by jgregmac** [comment]
Okay, I added some examples, and a link to my favorite online subnet calculator for further assistance.
